<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DestinationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('destinations')->insert([
            [
                'name' => 'Wana Wisata Baturraden',
                'slug' => Str::slug('Wana Wisata Baturraden'),
                'description' => 'Wana Wisata Baturraden merupakan hutan lindung dan tempat rekreasi yang ideal sebagai sarana pendidikan dan pengembangan ilmu pengetahuan juga dapat menimbulkan rasa cinta kepada alam.',
                'address' => 'Jl. Bumi Perkemahan Wana Wisata, Dusun I Karangmangu, Kemutug Lor, Kec. Baturaden, Kabupaten Banyumas, Jawa Tengah 53151',
                'maps_link' => 'https://maps.app.goo.gl/PLVRfeQAC3UYQQ8F7',
                'location' => 'Banyumas, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762651735/wana-wisata-baturraden_bczemp.png',
                'destination_category_id' => 1,
            ],
            [
                'name' => 'Telaga Sunyi',
                'slug' => Str::slug('Telaga Sunyi'),
                'description' => 'Telaga Sunyi Baturaden adalah sebuah destinasi wisata alam yang terletak di kawasan Baturaden,Kabupaten Banyumas,Jawa Tengah.Sesuai dengan namanya,telaga ini menawarkan suasana yang tenang dan damai,jauh dari keramaian kota,menjadikannya tempat yang ideal untuk menenangkan diri dan melepas penat.',
                'address' => 'Sawah & Hutan, Limpakuwus, Kec. Sumbang, Kabupaten Banyumas, Jawa Tengah 53183',
                'maps_link' => 'https://maps.app.goo.gl/WGxZmhny5EL7ysVbA',
                'location' => 'Banyumas, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762651937/telaga-sunyi_tyz0uf.jpg',
                'destination_category_id' => 1,
            ],
            [
                'name' => 'Pancuaran 3',
                'slug' => Str::slug('Pancuaran 3'),
                'description' => 'Pancuran 3 memiliki sejarah panjang yang diyakini sebagai petilasan Syekh Maulana Maghribi. Pancuran ini memiliki sumber air yang berasal dari Gunung Slamet. Pengunjung yang datang biasanya selain menikmati keindahan pancuran, juga mengunjungi petilasan. Yang menarik dari wisata ini ialah airnya yang panas dan berkhasiat.',
                'address' => 'Dusun III Kalipagu, Ketenger, Baturaden, Banyumas Regency, Central Java 53151, Ketenger, Baturraden',
                'maps_link' => 'https://maps.app.goo.gl/4ANrRUsgRAZXrj5z6',
                'location' => 'Banyumas, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762652272/pancuran-3_kxbw3m.jpg',
                'destination_category_id' => 1,
            ],
            [
                'name' => 'De Damaran',
                'slug' => Str::slug('De Damaran'),
                'description' => 'De Damaran, Wisata Alam yang dipersembahkan untuk liburan ringan sebagai taman hutan keluarga . Tersedia Jalur track, Playground, Campground area dan Campervan area, ATV, akses ke Taman Labirin Baturraden.',
                'address' => 'Dusun III Berubahan, Kemutug Lor, Kec. Baturaden, Kabupaten Banyumas, Jawa Tengah 53151',
                'maps_link' => 'https://maps.app.goo.gl/FEtj4X41FtAipuPx5',
                'location' => 'Banyumas, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762652434/de-damaran_jrstou.png',
                'destination_category_id' => 1,
            ],
            [
                'name' => 'Pancuran 7',
                'slug' => Str::slug('Pancuran 7'),
                'description' => 'Pancuran 7 Baturaden ini terkenal dengan keunikan tujuh pancuran air panas alami yang dapat dinikmati langsung oleh pengunjung. Air dari Pancuran ini mengandung belerang yang dipercaya memiliki manfaat untuk kesehatan kulit dan tubuh. Aliran airnya tidak hanya memberikan kesan menyegarkan, tetapi juga menciptakan pemandangan alam yang mempesona, dengan pepohonan hijau dan udara sejuk khas pegunungan Baturaden yang menyegarkan.',
                'address' => 'Dusun III Kalipagu, Ketenger, Kec. Baturaden, Kabupaten Banyumas, Jawa Tengah, Ketenger, Baturraden',
                'maps_link' => 'https://maps.app.goo.gl/oQzn9VLUrEMUEfLq6',
                'location' => 'Banyumas, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762653147/pancuran-7_vqbyin.jpg',
                'destination_category_id' => 1,
            ],
            [
                'name' => 'Hutan Pinus Limpakuwus',
                'slug' => Str::slug('Hutan Pinus Limpakuwus'),
                'description' => 'Hutan Pinus Limpakuwus adalah destinasi wisata alam yang menakjubkan yang menawarkan berbagai layanan dan aktivitas untuk semua jenis pengunjung. Dari cottage yang nyaman hingga petualangan outbound yang menantang, dari wahana menghibur hingga camping di alam terbuka, ada sesuatu untuk semua orang di sini.',
                'address' => 'Area Sawah, Limpakuwus, Kec. Sumbang, Kabupaten Banyumas, Jawa Tengah 53151',
                'maps_link' => 'https://maps.app.goo.gl/8VPvNZRP3NkXC1TQ9',
                'location' => 'Banyumas, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1759994180/HutanPinus_iv9pok.jpg',
                'destination_category_id' => 2,
            ],
            [
                'name' => 'Bukit Tengtung',
                'slug' => Str::slug('Bukit Tengtung'),
                'description' => 'Bukit Tengtung Baturaden yang terletak di kawasan wisata Baturaden yang menawarkan panorama sepektakuler yang memanjakan mata dengan pemandangan menakjubkan. Selain itu, Bukit Tengtung juga menjadi tempat yang ideal untuk menikmati matahari terbit atau terbenam sehingga sangat cocok untuk berfoto-foto.',
                'address' => 'Munggangsari, Karangsalam, Kec. Baturaden, Kabupaten Banyumas, Jawa Tengah 53126, Karangsalam, Baturraden',
                'maps_link' => 'https://maps.app.goo.gl/gFzvovgJvY5HnREX6',
                'location' => 'Banyumas, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762653480/bukit-tengtung_njgook.png',
                'destination_category_id' => 2,
            ],
            [
                'name' => 'Safari See To Sky',
                'slug' => Str::slug('Safari See To Sky'),
                'description' => 'Spot Alam terbaik di Jawa Tengah di 930 MDPL, berada di Kabupaten Banyumas, dengan keasrian alam kaki Gunung terbesar di Pulau Jawa , Gunung Slamet dengan alam yang asri dipadu udara sejuk khas atmosphere hutan tropis. Cafe 7G, menu kuliner kekinian dengan harga terjangkau di bawah hijau pepohonan dan menjadi tempat melepas lelah sambil menghirup segarnya oksigen. Safari Cafe & Resto menawarkan menu makanan dan minuman khas nusantara, tempat yang nyaman dengan view alam terbaik.',
                'address' => 'Kawasan, Safari See To Sky, Kec. Sumbang, Kabupaten Banyumas, Jawa Tengah 53183',
                'maps_link' => 'https://maps.app.goo.gl/EDDtoCy1n8dCSyk39',
                'location' => 'Banyumas, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762653763/safari-see-to-sky_hqkwjr.jpg',
                'destination_category_id' => 2,
            ],
            [
                'name' => 'Massapi Cafe & Resto',
                'slug' => Str::slug('Massapi Cafe & Resto'),
                'description' => 'Massapi Cafe ini ada di tengah rimbunnya hutan pinus, tepatnya di kawasan wisata Baturaden yang memang terkenal dengan udaranya yang dingin dan segar.',
                'address' => 'Dusun III Berubahan, Kemutug Lor, Kec. Baturaden, Kabupaten Banyumas, Jawa Tengah 53151',
                'maps_link' => 'https://maps.app.goo.gl/MUkUmMc86S1pbPrd7',
                'location' => 'Banyumas, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762654017/massapi_w9pnyd.jpg',
                'destination_category_id' => 2,
            ],
            [
                'name' => 'Pendakian Gn.slamet via Permadi Guci',
                'slug' => Str::slug('Pendakian Gn.slamet via Permadi Guci'),
                'description' => 'Basecamp Permadi Guci adalah salah satu jalur pendakian utama menuju Gunung Slamet via Tegal, dan juga berfungsi sebagai area bumi perkemahan (camping ground) dan wisata alam di kawasan objek wisata Guci.',
                'address' => 'Jl. Lingkar Barat No.10, RT.01/RW.01, Guci, Kecamatan Bumijawa, Kabupaten Tegal, Jawa Tengah 52466',
                'maps_link' => 'https://maps.app.goo.gl/aB8HLhUK1JbDTicY9',
                'location' => 'Tegal, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762654530/permadi-guci_ieopzl.png',
                'destination_category_id' => 2,
            ],
            [
                'name' => 'Pendakian Gn.slamet via Bambangan',
                'slug' => Str::slug('Pendakian Gn.slamet via Bambangan'),
                'description' => 'Jalur pendakian Bambangan adalah rute paling populer dan umum digunakan untuk mendaki Gunung Slamet, yang terletak di Desa Kutabawa, Kecamatan Karangreja, Purbalingga, Jawa Tengah. Jalur ini dikenal memiliki akses yang mudah dijangkau dan fasilitas basecamp yang cukup lengkap.',
                'address' => 'Dusun, Bambangan, Kutabawa, Kec. Karangreja, Kabupaten Purbalingga, Jawa Tengah 53357',
                'maps_link' => 'https://maps.app.goo.gl/fF22MkiFN7Sc6kdi9',
                'location' => 'Purbalingga, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762654894/bambangan_gtz9sw.png',
                'destination_category_id' => 2,
            ],
            [
                'name' => 'Curug Cipendok',
                'slug' => Str::slug('Curug Cipendok'),
                'description' => 'Curug Cipendok adalah air terjun dengan ketinggian 92 meter yang terletak di lereng Gunung Slamet. Curug Cipendok mempunyai daya tarik tersendiri, karena lingkungan masih betul-betul alami. Kesunyian juga masih sangat terasa, sebab belum banyak pelancong yang datang menikmati keindahan alamnya.',
                'address' => 'Dusun II Lebaksiu, Karanganyar, Karangtengah, Kec. Cilongok, Kabupaten Banyumas, Jawa Tengah 53162',
                'maps_link' => 'https://maps.app.goo.gl/iK242jK1Ms5cy7v18',
                'location' => 'Banyumas, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1759994095/CurugCipendok_rj0nyn.jpg',
                'destination_category_id' => 3,
            ],
            [
                'name' => 'Telaga Kumpe',
                'slug' => Str::slug('Telaga Kumpe'),
                'description' => 'Telaga Kumpe adalah destinasi wisata alam yang terletak di kaki Gunung Slamet, di Desa Gununglurah, Kecamatan Cilongok, Kabupaten Banyumas, Jawa Tengah. Tempat ini menawarkan suasana yang tenang dengan pemandangan alam yang masih asri dan udara yang sejuk, cocok untuk melepas penat dari hiruk pikuk perkotaan.',
                'address' => 'Dusun III, Gununglurah, Kec. Cilongok, Kabupaten Banyumas, Jawa Tengah 53162',
                'maps_link' => 'https://maps.app.goo.gl/iK242jK1Ms5cy7v18',
                'location' => 'Banyumas, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762655428/telaga-kumpe_dgww7n.png',
                'destination_category_id' => 3,
            ],
            [
                'name' => 'Pantai Menganti',
                'slug' => Str::slug('Pantai Menganti'),
                'description' => 'Pantai Menganti merupakan sebuah pantai yang berlokasi di Desa Karangduwur, Kecamatan Ayah, Kabupaten Kebumen, Jawa Tengah. Bentang alam pada Pantai Menganti terdiri dari perbukitan dan pasir putih. Sejak tahun 2011, Pantai Menganti menjadi tempat wisata dan selancar, sekaligus pelabuhan dan pelelangan ikan.',
                'address' => 'Tj. Karangboto, Karangduwur, Kec. Ayah, Kabupaten Kebumen, Jawa Tengah 54473',
                'maps_link' => 'https://maps.app.goo.gl/vM3JfvP5Hy6QqYon8',
                'location' => 'Kebumen, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1759994351/Menganti_oqcper.png',
                'destination_category_id' => 4,
            ],
            [
                'name' => 'Pantai Lampon',
                'slug' => Str::slug('Pantai Lampon'),
                'description' => 'Pantai Lampon merupakan salah satu destinasi wisata bahari yang terletak di Desa Pasir, Kecamatan Ayah, Kabupaten Kebumen, Jawa Tengah. Dikenal sebagai pantai yang masih alami dan relatif tersembunyi, Pantai Lampon menawarkan pemandangan alam yang menakjubkan dengan perpaduan pasir cokelat kehitaman, perbukitan hijau, dan air laut yang jernih.',
                'address' => 'Hutan, Pasir, Kec. Ayah, Kabupaten Kebumen, Jawa Tengah 54473',
                'maps_link' => 'https://maps.app.goo.gl/ASx87gRXjVMVh2qp7',
                'location' => 'Kebumen, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1759994514/Pantai-Lampon-Kebumen_eiueiy.jpg',
                'destination_category_id' => 4,
            ],
            [
                'name' => 'Pantai Surumanis',
                'slug' => Str::slug('Pantai Surumanis'),
                'description' => 'Pantai Surumanis adalah salah satu pantai tersembunyi yang belum banyak dikunjungi oleh wisatawan. Dikelilingi tebing karang dan hamparan pasir hitam kecoklatan yang unik, pantai ini menawarkan pemandangan alam yang masih sangat alami serta suasana tenang.',
                'address' => 'Dilem, Pasir, Kec. Ayah, Kabupaten Kebumen, Jawa Tengah 54473',
                'maps_link' => 'https://maps.app.goo.gl/TSmZLr5KW3C7NCeJ9',
                'location' => 'Kebumen, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1759994563/surumanis_hvnvei.jpg',
                'destination_category_id' => 4,
            ],
            [
                'name' => 'Curug Song',
                'slug' => Str::slug('Curug Song'),
                'description' => 'Curug Song adalah objek wisata air terjun yang di kelilingi oleh hutan pinus dan jati seluas 18 hektar. Curug ini memiliki air terjun utama dengan ketinggian sekitar 45 meter, serta Curug Dipacandra dengan ketinggian sekitar 25 meter. Selain keindahan alam, Curug Song juga menyediakan berbagai wahana rekreasi seperti kolam renang, flying fox dengan panjang tali sekitar 100 meter, ATV untuk menjelajahi hutan pineus, trampolin, dan sepeda gantung untuk berswafoto.',
                'address' => 'Area Sawah/Kebun, Kalisalak, Kec. Kebasen, Kabupaten Banyumas, Jawa Tengah 53172',
                'maps_link' => 'https://maps.app.goo.gl/xRVvJqP2BXmEQ3my8',
                'location' => 'Banyumas, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762655722/curug-song_i7brkn.png',
                'destination_category_id' => 4,
            ],
            [
                'name' => 'Menoreh Dreamland',
                'slug' => Str::slug('Menoreh Dreamland'),
                'description' => 'Menoreh Dreamland adalah destinasi wisata terpadu yang menggabungkan konsep restoran, kafe, dan tempat rekreasi alam di kawasan Perbukitan Menoreh, perbatasan Kulon Progo (Yogyakarta) dan Purworejo (Jawa Tengah). Tempat ini menawarkan suasana yang sejuk dengan pemandangan hutan pinus dan alam yang asri, cocok untuk liburan keluarga atau sekadar bersantai.',
                'address' => 'Sokomoyo, Jatimulyo, Kec. Girimulyo, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55674',
                'maps_link' => 'https://maps.app.goo.gl/7aYuiETuxTGmsCYz5',
                'location' => 'Kulon Progo, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762655956/menoreh-dreamland_myiokl.png',
                'destination_category_id' => 4,
            ],
            [
                'name' => 'Pantai Logending',
                'slug' => Str::slug('Pantai Logending'),
                'description' => 'Pantai Logending adalah destinasi wisata pantai eksotis yang terletak di Kecamatan Ayah, Kabupaten Kebumen, Jawa Tengah. Pantai ini terkenal dengan panorama alam yang indah, suasana yang sejuk, dan menjadi lokasi pertemuan antara pantai dengan muara sungai (Kali Bodo) yang membentuk laguna tenang.',
                'address' => 'Hutan, Argopeni, Kec. Ayah, Kabupaten Kebumen, Jawa Tengah',
                'maps_link' => 'https://maps.app.goo.gl/7FuJHkJjqWEYnR6b9',
                'location' => 'Kebumen, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762656234/pantai-logending_cjxqr4.png',
                'destination_category_id' => 4,
            ],
            [
                'name' => 'Gunung Selok',
                'slug' => Str::slug('Gunung Selok'),
                'description' => 'Gunung Selok merupakan daerah perbukitan yang menjulang menyerupai gunung dan kawasan hutan homogen tanaman mahoni. Hutan buatan yang dikelola oleh pihak Kantor Pemangku Hutan (KPH) Banyumas ini terdapat beberapa sanggar yang digunakan untuk ziarah atau beribadah, yaitu Jambe 5, Jambe & dan Padepokan Sang Hyang Gunung Jati.',
                'address' => 'Sawah,Ladang, Karangbenda, Kec. Adipala, Kabupaten Cilacap, Jawa Tengah',
                'maps_link' => 'https://maps.app.goo.gl/1K6DHV9gdmixzbK88',
                'location' => 'Cilacap, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1759994433/GunungSelok_fjjqin.jpg',
                'destination_category_id' => 4,
            ],
            [
                'name' => 'Kawah Sikidang',
                'slug' => Str::slug('Kawah Sikidang'),
                'description' => 'Kawah Sikidang merupakan lapangan perkawahan di Dataran Tinggi Dieng yang berada paling dekat dengan kawasan percandian Dieng, mudah diakses dan dinikmati karena terletak di tanah datar, sehingga juga menjadi kawah yang paling dikunjungi wisatawan.',
                'address' => 'Bakal Buntu, Dieng Kulon, Kec. Batur, Kab. Banjarnegara, Jawa Tengah 53456',
                'maps_link' => 'https://maps.app.goo.gl/Mw5gH6FBYvRnq2Cd8',
                'location' => 'Banjarnegara, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1759994248/KawahSikidang_hoedsb.jpg',
                'destination_category_id' => 5,
            ],
            [
                'name' => 'Gunung Pangonan',
                'slug' => Str::slug('Gunung Pangonan'),
                'description' => 'Gunung Pangonan adalah sebuah destinasi wisata alam yang terletak di Kawasan Dataran Tinggi Dieng, Jawa Tengah. Tempat ini terkenal karena menyajikan panorama alam berupa sabana atau padang rumput yang luas dan indah, sering disebut sebagai "Padang Savana Dieng".',
                'address' => 'Karangsari, Dieng Kulon, Kec. Batur, Kab. Banjarnegara, Jawa Tengah 53456',
                'maps_link' => 'https://maps.app.goo.gl/ZrqheuWhsX9oz43S6',
                'location' => 'Banjarnegara, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762658190/gunung-pangonan_bewohg.png',
                'destination_category_id' => 5,
            ],
            [
                'name' => 'Petak 9 / Dieng Park',
                'slug' => Str::slug('Petak 9 / Dieng Park'),
                'description' => 'Wana Wisata Petak 9 Bukit Sidengkeng Dieng merupakan sebuah bukit kecil di area kawasan wisata Telaga Warna yang menjadi salah satu tempat favorit wisatawan untuk memandang lanskap Telaga Warna dari atas. Obyek wisata ini sangat strategis untuk mendapatkan view Telaga Warna bersandingan dengan Telaga Pengilon dengan latar belakang perbukitan dan pegunungan yang mengelilinya.',
                'address' => 'Jl. Telaga Warna, Dieng, Kec. Kejajar, Kabupaten Wonosobo, Jawa Tengah 56354',
                'maps_link' => 'https://maps.app.goo.gl/mk8dRwNWuWfXFMRG8',
                'location' => 'Wonosobo, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762659209/dieng-park_wtmimr.png',
                'destination_category_id' => 5,
            ],
            [
                'name' => 'Bukit Sikunir',
                'slug' => Str::slug('Bukit Sikunir'),
                'description' => 'Bukit Sikunir merupakan salah satu wisata yang terletak di Desa Sembungan, Kecamatan Kejajar, Kabupaten Wonosobo. Bukit Sikunir berada pada ketinggian 2.300 MDPL (meter diatas permukaan laut). Wisata Bukit Sikunir menawarkan berbagai pemandangan gunung yang dapat diihat langsung diatas puncak, seperti Gunung Sindoro, Gunung Prau, dan Gunung Sumbing, Gunung Merbabu, Gunung Merapi, Gunung Lawu, Gunung Slamet, dan kawasan pegunungan lainnya yang dapat dilihat langsung saat cuaca cerah.',
                'address' => 'Jl. Telaga Cebong, Sawah & Hutan, Dieng, Kec. Kejajar, Kabupaten Wonosobo, Jawa Tengah',
                'maps_link' => 'https://maps.app.goo.gl/RF5m5kh4FdvBYz998',
                'location' => 'Wonosobo, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762659462/bukit-sikunir_phoab5.png',
                'destination_category_id' => 5,
            ],
            [
                'name' => 'Gunung Prau',
                'slug' => Str::slug('Gunung Prau'),
                'description' => 'Gunung Prau adalah gunung berapi non-aktif yang terletak di Dataran Tinggi Dieng, Jawa Tengah, Indonesia. Dikenal karena pemandangan matahari terbitnya yang spektakuler, gunung ini merupakan destinasi favorit bagi para pendaki, termasuk pemula, karena jalurnya yang relatif mudah.',
                'address' => 'Bakulan, Dieng, Wonosobo, Kabupaten Kendal, Jawa Tengah 51363',
                'maps_link' => 'https://maps.app.goo.gl/9wMVeb6gUu4ke3kM9',
                'location' => 'Kendal, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762660230/gunung-prau_nkqtd5.png',
                'destination_category_id' => 5,
            ],
            [
                'name' => 'Soko Langit',
                'slug' => Str::slug('Soko Langit'),
                'description' => 'Soko Langit adalah destinasi wisata dataran tinggi populer di Wonogiri, Jawa Tengah, yang terkenal dengan kolam renang infinity pool yang menawarkan pemandangan indah pegunungan dari ketinggian sekitar 1.000 meter di atas permukaan laut. Tempat ini cocok untuk healing dan bersantai dengan udara yang sejuk.',
                'address' => 'Nglarangan, Dusun Nglarangan, Conto, Kec. Bulukerto, Kabupaten Wonogiri, Jawa Tengah 57697',
                'maps_link' => 'https://maps.app.goo.gl/SEVBeWqkjkH174me7',
                'location' => 'Wonogiri, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762661939/soko-langit_bb6hhu.png',
                'destination_category_id' => 5,
            ],
            [
                'name' => 'Kali Paingan',
                'slug' => Str::slug('Kali Paingan'),
                'description' => 'Wisata Kali Paingan terletak di petak 56 Resort Paninggaran Bagian Kesatuan BKPH Paninggaran, Perhutani Kesatuan Pemangkuan Hutan (KPH) Pekalongan Timur dengan keluasan  2,0 hektar  masuk wilayah administratif desa  Tenogo,  Paninggaran Kabupaten Pekalongan. Wisata bernuansa aliran sungai yang jernih dan berbatu-batu  dikelilingi hamparan hutan pinus. Lokasi tersebut dapat ditempuh sekitar  40 Km arah selatan dari kota Pekalongan.',
                'address' => 'Hutan, Tenogo, Kec. Paninggaran, Kabupaten Pekalongan, Jawa Tengah 51164',
                'maps_link' => 'https://maps.app.goo.gl/AQWta3HqN2gftY3h8',
                'location' => 'Pekalongan, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762662139/kali-paingan_v3zuk0.png',
                'destination_category_id' => 5,
            ],
            [
                'name' => 'Curug Sinom Indah',
                'slug' => Str::slug('Curug Sinom Indah'),
                'description' => 'Curug Sinom Indah adalah destinasi wisata alam berupa air terjun yang terletak di tengah hutan pinus di Kabupaten Banjarnegara, Jawa Tengah. Tempat ini menawarkan suasana yang sejuk, asri, dan damai, cocok untuk bersantai dan menikmati alam.',
                'address' => 'Area Hutan/Perkebunan, Kasinoman, Kec. Kalibening, Kab. Banjarnegara, Jawa Tengah 53458',
                'maps_link' => 'https://maps.app.goo.gl/2R3a6fDzBBk1gibi6',
                'location' => 'Banjarnegara, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762662315/curug-sinom-indah_rwnqgw.png',
                'destination_category_id' => 5,
            ],
            [
                'name' => 'Kalianget Mangunan',
                'slug' => Str::slug('Kalianget Mangunan'),
                'description' => '"Kali Anget" (atau Kalianget) merujuk pada beberapa lokasi, tetapi yang paling terkenal adalah Taman Rekreasi Kalianget di Wonosobo, Jawa Tengah, yang merupakan pemandian air panas alami.',
                'address' => 'Jl. Kalibening - Gripit, Jogjogan, Kalibening, Kec. Kalibening, Kab. Banjarnegara, Jawa Tengah 53458',
                'maps_link' => 'https://maps.app.goo.gl/PJJ1YZZTUBrE5Yvn7',
                'location' => 'Banjarnegara, Jawa Tengah',
                'main_image_url' => 'https://res.cloudinary.com/djfxfwzin/image/upload/v1762662545/kalianget-mangunan_xvinxs.png',
                'destination_category_id' => 5,
            ],


        ]);
    }
}
